# Generated by Django 3.2.5 on 2021-07-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='note',
            field=models.CharField(default='', max_length=255),
        ),
    ]
