# Generated by Django 3.2.5 on 2021-07-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_task_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.CharField(max_length=255),
        ),
    ]
