# Generated by Django 3.2.5 on 2021-07-22 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_task_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='note',
        ),
        migrations.AddField(
            model_name='entry',
            name='note',
            field=models.CharField(default='', max_length=255),
        ),
    ]
